-- Q-1. What is the total revenue generated by male vs female Customers ? 
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q-2. Which Customer used a discount but still spend more than the average purchase amount ?
SELECT customer_id, purchase_amount 
FROM customer
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer); 

SELECT * FROM customer;

-- Q-3. Which are the top 5 products with highest average review rating ?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q-4. Compare the average Purchase Amounts between  Standard and Express Shipping
SELECT shipping_type,
AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;


-- Q-5. Do Subscribed Customers spend more ? Compare Average spend and total revenue between Subscribers and Non-Subscribers ?
SELECT subscription_status, COUNT (customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as avg_spend, 
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
GROUP BY  subscription_status
ORDER BY total_revenue, avg_spend DESC;

SELECT * FROM customer;

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*), 2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

SELECT * from customer;

SELECT current_user;

